apiVersion: apps/v1
kind: Deployment
metadata:
  name: meeting-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: meeting-app
  template:
    metadata:
      labels:
        app: meeting-app
    spec:
      containers:
      - name: meeting-app
        image: meeting-app:1.0
        ports:
        - containerPort: 8080
        imagePullPolicy: Never

---
apiVersion: v1
kind: Service
metadata:
  name: meeting-app
spec:
  selector:
    app: meeting-app
  ports:
  - port: 8080
  type: NodePort